name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > hospital-key.pem
          chmod 600 hospital-key.pem

      - name: Build & Deploy on EC2
        run: |
          ssh -i hospital-key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            set -e

            APP_DIR=/home/ec2-user/hospital-appointment
            ENV_FILE=/home/ec2-user/hospital.env

            echo "Checking env file..."
            if [ ! -f "$ENV_FILE" ]; then
              echo "❌ hospital.env not found"
              exit 1
            fi

            echo "Cloning or updating repository..."
            if [ ! -d "$APP_DIR" ]; then
              git clone https://github.com/aksah72/hospital_app.git $APP_DIR
            fi

            cd $APP_DIR
            git pull origin main

            echo "Stopping old container..."
            sudo docker stop hospital-app || true

            echo "Removing old container..."
            sudo docker rm hospital-app || true

            echo "Building new Docker image..."
            sudo docker build -t hospital-app:latest .

            echo "Running new container..."
            sudo docker run -d \
              --name hospital-app \
              --env-file $ENV_FILE \
              -p 3000:3000 \
              hospital-app:latest

            echo "✅ Deployment completed successfully"
          EOF
