name: Deploy to EC2 Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Save EC2 private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy container to EC2
  run: |
    ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF

      echo "Pulling latest image..."
      sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hospital-app:latest

      echo "Stopping old container..."
      sudo docker stop hospital-app || true

      echo "Removing old container..."
      sudo docker rm hospital-app || true

      echo "Running new container..."
      sudo docker run -d --name hospital-app -p 80:3000 \
        ${{ secrets.DOCKERHUB_USERNAME }}/hospital-app:latest

    EOF

