name: Deploy to EC2 Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Save EC2 private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy container to EC2
        run: |
         ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF

  echo "Stopping all containers..."
  sudo docker ps -aq | xargs -r sudo docker stop

  echo "Removing all containers..."
  sudo docker ps -aq | xargs -r sudo docker rm -f

  echo "Cleaning port 80 listeners..."
  sudo lsof -t -i:80 | xargs -r sudo kill -9

  echo "Pulling latest image..."
  sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest

  echo "Starting fresh container..."
  sudo docker run -d --name hospital_app -p 80:3000 \
    ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest

EOF

