name: Deploy to EC2 Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Save EC2 private key
      - name: Save EC2 SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      # SSH and deploy container
      - name: Deploy container on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hospital-app:latest
            sudo docker stop hospital-app || true
            sudo docker rm hospital-app || true
            sudo docker run -d --name hospital-app -p 3000:3000 \
              ${{ secrets.DOCKERHUB_USERNAME }}/hospital-app:latest
          EOF
