name: Deploy to EC2 Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Save EC2 private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy container to EC2
  run: |
    ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'

      echo "Cleaning old containers..."
      sudo docker stop hospital-app || true
      sudo docker rm hospital-app || true

      echo "Pulling latest image..."
      sudo docker pull aksah22/hospital-app:latest

      echo "Running new container with env variables..."
      sudo docker run -d --name hospital-app \
        -p 3000:3000 \
        -e MONGODB_URI="${{ secrets.MONGODB_URI }}" \
        -e SESSION_SECRET="${{ secrets.SESSION_SECRET }}" \
        aksah22/hospital-app:latest

      echo "Deployment completed!"
    EOF


